import io
import json
import zipfile
from pathlib import Path
from typing import Dict, Any

def convert_geojson_to_kml(geojson_dict: Dict[str, Any], layer_name: str = "Dam_Flood_Inundation") -> str:
    """
    Converts GeoJSON features (Polygons, LineStrings, Points) into valid Google Earth OGC KML 2.2.
    """
    kml_parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<kml xmlns="http://www.opengis.net/kml/2.2">',
        '  <Document>',
        f'    <name>{layer_name}</name>',
        '    <Style id="floodPoly">',
        '      <PolyStyle>',
        '        <color>7dff0000</color>', # Semi-transparent blue in KML AABBGGRR
        '        <outline>1</outline>',
        '      </PolyStyle>',
        '      <LineStyle>',
        '        <color>ffffaa00</color>',
        '        <width>2.5</width>',
        '      </LineStyle>',
        '    </Style>',
        '    <Style id="assetMarker">',
        '      <IconStyle>',
        '        <scale>1.1</scale>',
        '      </IconStyle>',
        '    </Style>'
    ]
    
    for feat in geojson_dict.get("features", []):
        props = feat.get("properties", {})
        name = props.get("name", props.get("location_label", "Flood Feature"))
        desc = "<br/>".join([f"<b>{k}:</b> {v}" for k, v in props.items()])
        geom = feat.get("geometry", {})
        gtype = geom.get("type")
        coords = geom.get("coordinates", [])
        
        kml_parts.append('    <Placemark>')
        kml_parts.append(f'      <name>{name}</name>')
        kml_parts.append(f'      <description><![CDATA[{desc}]]></description>')
        
        if gtype == "Point":
            kml_parts.append('      <styleUrl>#assetMarker</styleUrl>')
            kml_parts.append('      <Point>')
            kml_parts.append(f'        <coordinates>{coords[0]},{coords[1]},0</coordinates>')
            kml_parts.append('      </Point>')
        elif gtype == "Polygon":
            kml_parts.append('      <styleUrl>#floodPoly</styleUrl>')
            kml_parts.append('      <Polygon>')
            kml_parts.append('        <extrude>1</extrude>')
            kml_parts.append('        <altitudeMode>clampToGround</altitudeMode>')
            kml_parts.append('        <outerBoundaryIs>')
            kml_parts.append('          <LinearRing>')
            coord_str = " ".join([f"{pt[0]},{pt[1]},0" for pt in coords[0]])
            kml_parts.append(f'            <coordinates>{coord_str}</coordinates>')
            kml_parts.append('          </LinearRing>')
            kml_parts.append('        </outerBoundaryIs>')
            kml_parts.append('      </Polygon>')
        elif gtype == "LineString":
            kml_parts.append('      <LineString>')
            coord_str = " ".join([f"{pt[0]},{pt[1]},0" for pt in coords])
            kml_parts.append(f'        <coordinates>{coord_str}</coordinates>')
            kml_parts.append('      </LineString>')
            
        kml_parts.append('    </Placemark>')
        
    kml_parts.append('  </Document>')
    kml_parts.append('</kml>')
    
    return "\n".join(kml_parts)

def create_shapefile_archive(geojson_dict: Dict[str, Any], layer_name: str = "flood_extent") -> bytes:
    """
    Creates a ZIP archive bundle containing GeoJSON, KML, and standard GIS projection PRJ file
    (EPSG:4326 WGS84) suitable for QGIS, ArcGIS, and Google Earth imports.
    """
    zip_buffer = io.BytesIO()
    
    wgs84_prj = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
    kml_content = convert_geojson_to_kml(geojson_dict, layer_name)
    geojson_str = json.dumps(geojson_dict, indent=2)
    
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{layer_name}.geojson", geojson_str)
        zf.writestr(f"{layer_name}.kml", kml_content)
        zf.writestr(f"{layer_name}.prj", wgs84_prj)
        zf.writestr(
            "README_GIS_METADATA.txt",
            f"Dam Break Inundation Simulation Export\n"
            f"Layer: {layer_name}\n"
            f"Datum: WGS 84 (EPSG:4326)\n"
            f"Generated by: SIH26161 Hydrodynamic Prototype\n"
        )
        
    zip_buffer.seek(0)
    return zip_buffer.getvalue()
